### ISSUE TITLE
Some Characters Missing in Image Generated by pdfium

### ISSUE THREAD

**Issue by KameshRajendran** [bblanchon/pdfium-binaries#167] opened 2024-06-13 13:29 UTC
Hi Team,

We have been trying to convert a PDF document into an image using pdfium.wasm, but the generated document is missing some characters. However, when we use pdfium.dll for the conversion, it works correctly. Our project relies on pdfium.wasm, and it fails in these scenarios.

We downloaded the latest version of pdfium.wasm from the following link:

https://github.com/bblanchon/pdfium-binaries?tab=readme-ov-file#download 

Please check the live sample below, which uses pdfium.wasm to convert PDFs into images: https://pdfviewer.github.io/

Replication steps:

1. Open the GitHub sample link above.
2. Upload the attached PDF document.
3. Click the “Process file” button.

Document 
[example.pdf](https://github.com/user-attachments/files/15821231/example.pdf)

 |  Image generated using pdfium.dll     | Image generated using pdfium.wasm     |
| :---: | :---: |
| ![image](https://github.com/bblanchon/pdfium-binaries/assets/25635968/5af4c613-0979-46ae-9c95-7eeacbae6028) |  ![image](https://github.com/bblanchon/pdfium-binaries/assets/25635968/00a29bd2-a335-4b02-a319-9937f5744de0)   |

Could you please investigate and provide a solution to resolve this issue, as it is affecting our production sites?

**Comment by bblanchon** [comment] 2024-06-14 06:55
Duplicate of #163

**Closed by bblanchon** 2024-06-14 06:55 UTC
