### ISSUE TITLE
FPDF_SetPrintTextWithGDI missing

### ISSUE THREAD

**Issue by danz68** [bblanchon/pdfium-binaries#11] opened 2018-11-30 09:32 UTC
It seems PDFium is built without #defining **PDFIUM_PRINT_TEXT_WITH_GDI**, therefore **FPDF_SetPrintTextWithGDI** function is missing.

Can this be added for Windows dlls?

**Comment by bblanchon** [comment] 2019-02-06 14:06
Please apologize for the late answer; I missed your message because notifications were turned off.

This API is marked as experimental; I'm not sure it's wise to enable it.
What's your experience on that?

**Comment by danz68** [comment] 2019-02-06 17:28
I have no experience with that, but it might worth to try, eventually is a developer option. In current build, the pdf output approximates the glyphs with paths, I would gladly try the experimental GDI text print, if you would enable it.

**Comment by bblanchon** [comment] 2019-02-07 14:40
The problem is that I want to provide a binary that is suitable for most users.
I'm looking at the 99% here; I know I cannot satisfy the remaining 1%.

Unless we are sure that this flag doesn't break any code, I cannot enable it, I'm sorry.

But you know, it's like that for any project: the pre-cooked binaries are for the standard user. If you need different compilation options, you have to compile it yourself.

**Comment by danz68** [comment] 2019-02-07 15:19
I have no problem with the way you setup your binaries' compiling options. Would have been interesting to see the differences, with GDI text print, even if it is marked a experimental, that's all. 

As far as I heard it is quite of a complex setup for pdfium project, but it is possible if that option would prove crucial to create the environment myself. Till then I am grateful with the output as it is now.

**Comment by lukas-w** [comment] 2019-03-30 11:46
+1 on enabling `PDFIUM_PRINT_TEXT_WITH_GDI`. As far as I can see, adding this define only adds functionality and does not change anything by itself. To actually enable it, `FPDF_SetPrintTextWithGDI` has to be called first. Without this flag, the implementation is simply missing, see e.g. [`CGdiPrinterDriver::DrawDeviceText`](https://github.com/lukas-w/pdfium/blob/1bdc49a48802acfb6bd4b3e531dda08d0bbaa332/core/fxge/win32/fx_win32_print.cpp#L200-L208). Chrome always [has this flag enabled](https://github.com/chromium/chromium/blob/42506161bd1d376b6b858cce18bc0a0d93c89390/build_overrides/pdfium.gni#L22).

**Comment by bblanchon** [comment] 2019-04-06 08:03
Hi @danz68 and @lukas-w,

[Today's build](https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F3758) should have the option enabled, can you check?

Regards,
Benoit

**Comment by lukas-w** [comment] 2019-06-18 10:28
Sorry for not getting back to you @bblanchon. Unfortunately, the option is not enabled. I believe `pdf_use_win32_gdi_override` is overwritten in [`build_overrides/pdfium.gni`](https://pdfium.googlesource.com/pdfium/+/refs/heads/master/build_overrides/pdfium.gni#32). I think using `pdf_use_win32_gdi = true` in `args/windows.args.gn` should work.

**Closed** 2019-06-27 06:34 UTC
